### ISSUE TITLE
Segmentation fault (core dumped) Error

### ISSUE THREAD

**Issue by sanjaysingh765** [MaayanLab/clustergrammer-py#2]
I tried to make the cluster for my dataset (55K genes, 37 samples) but I am getting the error Segmentation fault (core dumped). I also tried to make cluster online by your sever but it failed. Is it possible to overcome this problem?

**Comment by cornhundred** [comment]
This might be because you ran out of memory (see stackoverflow [link](http://stackoverflow.com/a/31048386/3957721)). You will probably want to filter your genes (rows) down to ~1,000 to ~5,000 to prevent this from happening. You can do this using the clustergrammer network object before you run your calculation (see example [make_clustergrammer.py](https://github.com/MaayanLab/clustergrammer/blob/master/make_clustergrammer.py))

```
# filter for the top 1000 rows based on sum
net.filter_N_top('row', 1000, rank_type='sum')

# filter for the top 1000 rows based on variance
net.filter_N_top('row', 1000, rank_type='var')
```

You can also turn off the similarity matrix calculation when you cluster using 
```
net.make_clust(sim_mat=False) 
```
which will prevent it from trying to cluster the large row-row similarity matrix.
(Also, we're working on increasing the amount of data that can be handled on the front-end.)

 Let me know if that helps.

**Comment by sanjaysingh765** [comment]
I know that this is a memory related problem. I was curious that if there are is any way around to cluster the large matrix.  Thanks though.

**Comment by cornhundred** [comment]
Okay, so I'm pretty sure its an isssue with the SciPy library (being called [here](https://github.com/MaayanLab/clustergrammer-py/blob/master/clustergrammer/calc_clust.py)). I'll let you know if I can find anything more about this.
